### ISSUE TITLE
Warp to template operator: error in output image...

### ISSUE THREAD

**Issue by alveniz** [DHI-GRAS/sen-et-snap-sta#1]
Hi, thanks for the project http://esa-sen4et.org/

I testing your plugins in snap 7.0 in windows and ubuntu, but I have problems for the operator: Warp to template operator, this operator distorts the image changing the order of pixels:
![error warp operator](https://user-images.githubusercontent.com/58125725/69488308-ae62fd80-0e35-11ea-9eb5-b4ac5b534a56.jpg)

this python results...:

```
C:\Users\ALVENI~1\AppData\Local\Temp>"C:\Users\alvenizpit\.snap\auxdata\sen-et-conda-Win64\sen-et-snap-scripts\\..\python.exe" "C:\Users\alvenizpit\.snap\auxdata\sen-et-conda-Win64\sen-et-snap-scripts\\warp_to_template.py" --resample_algorithm cubicspline --output "C:\Users\alvenizpit\Documents\Cathe Maestria\test\eldelcaso.dim" --source "C:\Users\alvenizpit\Documents\Cathe Maestria\anteproyecto\datos size 3 ete pc\S3a_20190104\!OUTPUT_observation_geometry!.dim" --template "C:\Users\alvenizpit\Documents\Cathe Maestria\anteproyecto\datos size 3 ete pc\s2a_20190104\!OUTPUT_SRTM_elevation!.dim" 
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
INFO: org.esa.snap.core.util.EngineVersionCheckActivator: Please check regularly for new updates for the best SNAP experience.
INFO: org.hsqldb.persist.Logger: dataFileCache open start
INFO: org.esa.snap.dataio.bigtiff.BigGeoTiffProductWriter: writing to output file C:\Users\ALVENI~1\AppData\Local\Temp\tmpvadbo3c8.tif
INFO: org.esa.snap.dataio.bigtiff.BigGeoTiffProductWriter: writing to output file C:\Users\ALVENI~1\AppData\Local\Temp\tmpvipat9y2.tif
Warning 1: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
Finished tool execution in 91 seconds
```

thank you...

**Comment by alveniz** [comment]
@georgeboldeanu,  @j08lue, any idea for this error in "Warp to template operator":

thanks!!!!!!!!!!

**Comment by georgeboldeanu** [comment]
@alveniz  Personally i didn't test this operator.

**Comment by j08lue** [comment]
Could you please provide your input parameters, @alveniz? Then we can try to reproduce the error.

Btw, the operator calls [this Python script](https://github.com/DHI-GRAS/sen-et-snap-scripts/blob/5df700e1095289d054f0d7f9c9c4e9a569dcf26d/warp_to_template.py).

**Comment by radosuav** [comment]
To me it looks like memory error. @alveniz could you also upload the input files to https://nextcloud03.webo.hosting/s/Wkn7RSEqipy8rfj.

**Comment by panakouris** [comment]
@alveniz on my end, I tried the operator `warp to template` and is working as expected. As inputs I used, the observation geometry product as produced from the `Sentinel-3-preprocessing graph` and the reflactance product as produced from the `Sentinel-2-preprocessing graph`. If you use the same inputs, and still getting this error, I would advice you to check sen-et user manual troubleshooting (3.4.3) and verify that that the products that you get from preprocessing graphs include only a subset of the available bands. We have seen that sometimes the built-in SNAP subset operator is not working as expected.

**Comment by alveniz** [comment]
> Could you please provide your input parameters, @alveniz? Then we can try to reproduce the error.
> 
> Btw, the operator calls [this Python script](https://github.com/DHI-GRAS/sen-et-snap-scripts/blob/5df700e1095289d054f0d7f9c9c4e9a569dcf26d/warp_to_template.py).

thanks @j08lue, these are the parameters,:
![image](https://user-images.githubusercontent.com/58125725/72926352-4be98900-3d22-11ea-89f3-01270ce281a3.png)
![image](https://user-images.githubusercontent.com/58125725/72926380-586de180-3d22-11ea-8d33-6f9767ffc277.png)

`C:\Users\ALVENI~1\AppData\Local\Temp>"C:\Users\alvenizpit\.snap\auxdata\sen-et-conda-Win64\sen-et-snap-scripts\\..\python.exe" "C:\Users\alvenizpit\.snap\auxdata\sen-et-conda-Win64\sen-et-snap-scripts\\warp_to_template.py" --resample_algorithm cubicspline --output C:\Users\alvenizpit\Documents\warptest.dim --source "D:\ubuntu\datos size 5 sen-et enero 2020\S3a_20190104\!OUTPUT_observation_geometry!.dim" --template "D:\ubuntu\datos size 5 sen-et enero 2020\S2a_20190104\!OUTPUT_reflectance!.dim" 
INFO: org.esa.snap.python.gpf.PyOperatorSpi: Python operator 'S2RutOp' registered (Python module: 's2_rut', class: 'S2RutOp', root: 'C:\Program Files\snap\s2tbx\modules\org-esa-snap-snap-rut.jar')
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
INFO: org.esa.snap.core.util.EngineVersionCheckActivator: Please check regularly for new updates for the best SNAP experience.
INFO: org.hsqldb.persist.Logger: dataFileCache open start
INFO: org.esa.snap.dataio.bigtiff.BigGeoTiffProductWriter: writing to output file C:\Users\ALVENI~1\AppData\Local\Temp\tmphmklj32k.tif
INFO: org.esa.snap.dataio.bigtiff.BigGeoTiffProductWriter: writing to output file C:\Users\ALVENI~1\AppData\Local\Temp\tmp2s30kvua.tif
Warning 1: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
Warning 1: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
Finished tool execution in 128 seconds
`

**Comment by alveniz** [comment]
Hi all, @georgeboldeanu @j08lue @radosuav thanks for your replies...

This is the results of operator, and the source images, please see attached:
this links of data:
link SentinelOutputsGraph: https://drive.google.com/open?id=0B3As4rI2uISuejc5RFNxOWs4RnFTdVVEMW1LVTJtTlljTWI4

link WarpResult: https://drive.google.com/open?id=0B3As4rI2uISuSzZjcWlsNFNFZ2pHc0Y5Mm1PWGYzdmlqd3hB

S2 Reflectance, source image: "S2A_MSIL2A_20190104T152631_N0211_R025_T18NUL_20190104T192952.SAFE"

![IMG-20200123-WA0002](https://user-images.githubusercontent.com/58125725/73016558-14dfaa00-3dec-11ea-91ce-c0a1b8844bbb.jpg)

S2 Reflectance image as 22 x 25 pixeles
![IMG-20200123-WA0003](https://user-images.githubusercontent.com/58125725/73016598-2aed6a80-3dec-11ea-8c86-3aa279f74bc1.jpg)

S3 Geometry product, source image: "S3A_SL_2_LST____20190104T144629_20190104T162728_20190106T002626_6059_040_025______LN2_O_NT_003.SEN3"
![IMG-20200123-WA0004](https://user-images.githubusercontent.com/58125725/73016643-40fb2b00-3dec-11ea-898e-604ba8c3217e.jpg)

Parameters of warp operator:
![IMG-20200123-WA0005](https://user-images.githubusercontent.com/58125725/73016692-5a03dc00-3dec-11ea-8c77-39ae8f6044e3.jpg)

![IMG-20200123-WA0006](https://user-images.githubusercontent.com/58125725/73016730-6b4ce880-3dec-11ea-8551-73ac765e3c36.jpg)

Code:
`C:\Users\ALVENI~1\AppData\Local\Temp>"C:\Users\alvenizpit\.snap\auxdata\sen-et-conda-Win64\sen-et-snap-scripts\\..\python.exe" "C:\Users\alvenizpit\.snap\auxdata\sen-et-conda-Win64\sen-et-snap-scripts\\warp_to_template.py" --resample_algorithm cubicspline --output C:\Users\alvenizpit\Documents\WArpResult.dim --source "D:\ubuntu\datos size 5 sen-et enero 2020\S3a_20190104\!OUTPUT_observation_geometry!.dim" --template "D:\ubuntu\datos size 5 sen-et enero 2020\S2a_20190104\!OUTPUT_reflectance!.dim" 
INFO: org.esa.snap.python.gpf.PyOperatorSpi: Python operator 'S2RutOp' registered (Python module: 's2_rut', class: 'S2RutOp', root: 'C:\Program Files\snap\s2tbx\modules\org-esa-snap-snap-rut.jar')
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
INFO: org.esa.snap.core.util.EngineVersionCheckActivator: Please check regularly for new updates for the best SNAP experience.
INFO: org.hsqldb.persist.Logger: dataFileCache open start
INFO: org.esa.snap.dataio.bigtiff.BigGeoTiffProductWriter: writing to output file C:\Users\ALVENI~1\AppData\Local\Temp\tmpqcgdcayc.tif
INFO: org.esa.snap.dataio.bigtiff.BigGeoTiffProductWriter: writing to output file C:\Users\ALVENI~1\AppData\Local\Temp\tmpozlgtl8a.tif
Warning 1: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
Warning 1: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
Finished tool execution in 18 seconds
`

The Warp Result, see the raster size "25x22", Is it the expected result?
![IMG-20200123-WA0007](https://user-images.githubusercontent.com/58125725/73016746-76077d80-3dec-11ea-8c46-403b83f45434.jpg)

thanks!!!!!

**Comment by panakouris** [comment]
Hi @alveniz! Thanks for the extended report and for providing your data. We were able to find and fix the reported bug. I pushed the new bundle. You can either re-install the whole bundle by re-installing the plugin or simply delete the directory `<USEPROFILE>\.snap\auxdata\sen-et-conda-Win64\sen-et-snap-scripts\` and clone [this](https://github.com/DHI-GRAS/sen-et-snap-scripts) repository into `<USEPROFILE>\.snap\auxdata\sen-et-conda-Win64\` to avoid re-installing all the required packages.

**Comment by alveniz** [comment]
thanks, its work
