### ISSUE TITLE
Error in operator 3.3.7 Produce maps of vegetation structural parameters

### ISSUE THREAD

**Issue by rasc1974** [DHI-GRAS/sen-et-snap-sta#11]
Hi Radoslaw,
the following error apears, while processing operator 3.3.7: 
"_ERROR:K:\SEN-ET\Wernikow\20180726\Wernikow_OUTPUT_20180726_CCI_landcover.dim does not contain band CCILandCover-2015_" but I created the landcover-Output before (step 3.3.4), however the band in the Output of 3.3.4 is called "land_cover_CCILandCover-2015".
Regards
Rainer

**Comment by radosuav** [comment]
Hi Rainer,
You need to type the correct band name in the "Land-cover band" parameter field:
![image](https://user-images.githubusercontent.com/4759850/77729435-f0c46300-6ffe-11ea-8bd7-f557ff4fff94.png)
So in your case this field should have a value of "land_cover_CCILandCover-2015".

**Comment by rasc1974** [comment]
Thank You. Now it works... :-)
