### ISSUE TITLE
Error in Sentinel 3 pre-processing graph?

### ISSUE THREAD

**Issue by rasc1974** [DHI-GRAS/sen-et-snap-sta#12]
Hi - once again,

I´d like to pre-process a Sentinel 3-file with the corresponding graph. However an error occurs: "_Undefined symbol 'cloud_in'_". I did not make any changes to the Sentinel 3 file before, the file was downloaded by using the 'Download sentinel data' - operator.

![SNAP_Sen3_preprocessing](https://user-images.githubusercontent.com/62097421/78127175-fca39100-7413-11ea-8e30-a7147c9e9f79.PNG)

Regards,
Rainer

**Comment by radosuav** [comment]
Hi Rainer,
SNAP graph GUI can be quite buggy, especially when working with Sentinel-3 data. That's why in the user manual (section 3.3.1 on page 19) we recommend to edit the graph in a text editor and then to open it in SNAP just to run.

**Comment by rasc1974** [comment]
Dear Radoslaw,

thanks. I edited the xml in Notepad, now. The subset to a specific geographic region and the settings of the Output file-folders and -names seems to work. But the same error apears again.

Best regards
Rainer

**Comment by radosuav** [comment]
Does the error appear when you press Run or when the graph is loaded and you switch to a different operator tab? If it's the latter then try pressing Run, it should execute fine.

**Comment by rasc1974** [comment]
Hi,
it apears, when I switch from one tab to another, after the operator is loaded. Following your recommendation, I didn´t do that anymore. Now it works.... :) 
Is it correct, that I can´t open the 'LST' and the 'observation_geometry' product in SNAP, later?
Regards
Rainer

**Comment by radosuav** [comment]
Good to hear that it works. Once the graph is finished you should be able to open the output products in SNAP normally. However, please also have a look at section 3.4.3 (SNAP subset operator does not subset bands) of the user manual.

**Comment by rasc1974** [comment]
There are three Outputs in 3.3.9 (observation_geometry, mask and LST). These apear within the defined output folder (a *.dim-file and a *.data-folder). However only mask.dim can be opened in SNAP afterwards. LST and observation_geometry can be selected via 'File' > 'Open Product' but nothing happens.

Alternatively I tried to follow the instructions in 3.4.3 and created a new graph and applied it to the original SEN 3 product to produce a subset-file. Subset means limited to a geografic region and to the following bands: '<sourceBands>LST,cloud_in,sat_zenith_tn,solar_zenith_tn,latitude_tx,longitude_tx</sourceBands>'

Afterwards I used the new subset-file as input in 3.3.9 and got the same result as above (mask, LST and observation_geometry, but only mask can be opened in SNAP).

**Comment by radosuav** [comment]
Are any errors reported while the graph is running or when it's finished? An error message can appear as a small icon in the bottom-right of SNAP window. Also, how much RAM do you have on your computer? It is possible that this is a memory issue.

**Comment by rasc1974** [comment]
Here is the log from that procedure: 

java.lang.IllegalArgumentException: The Product 'Isterbis_20190625_Sen3_OUTPUT_observation_geometry' already contains a band with the name 'confidence_in_duplicate'.
	at com.bc.ceres.core.Assert.argument(Assert.java:67)
	at org.esa.snap.core.datamodel.Product.addBand(Product.java:1121)
	at org.esa.snap.core.dataio.dimap.DimapProductHelpers$ProductBuilder.addBand(DimapProductHelpers.java:1734)
	at org.esa.snap.core.dataio.dimap.DimapProductHelpers$ProductBuilder.addSpectralBands(DimapProductHelpers.java:1606)
	at org.esa.snap.core.dataio.dimap.DimapProductHelpers$ProductBuilder.addBands(DimapProductHelpers.java:1583)
	at org.esa.snap.core.dataio.dimap.DimapProductHelpers$ProductBuilder.createProduct(DimapProductHelpers.java:1136)
	at org.esa.snap.core.dataio.dimap.DimapProductHelpers$ProductBuilder.access$100(DimapProductHelpers.java:1111)
	at org.esa.snap.core.dataio.dimap.DimapProductHelpers.createProduct(DimapProductHelpers.java:116)
	at org.esa.snap.core.dataio.dimap.DimapProductReader.processProduct(DimapProductReader.java:138)
	at org.esa.snap.core.dataio.dimap.DimapProductReader.readProductNodesImpl(DimapProductReader.java:117)
	at org.esa.snap.core.dataio.AbstractProductReader.readProductNodes(AbstractProductReader.java:169)
	at org.esa.snap.engine_utilities.gpf.CommonReaders.read(CommonReaders.java:80)
	at org.esa.snap.engine_utilities.gpf.CommonReaders.readCommonProductReader(CommonReaders.java:51)
	at org.esa.snap.engine_utilities.gpf.CommonReaders.readProduct(CommonReaders.java:33)
	at org.esa.snap.graphbuilder.rcp.dialogs.GraphBuilderDialog.openTargetProducts(GraphBuilderDialog.java:689)
	at org.esa.snap.graphbuilder.rcp.dialogs.GraphBuilderDialog.access$900(GraphBuilderDialog.java:66)
	at org.esa.snap.graphbuilder.rcp.dialogs.GraphBuilderDialog$ProcessThread.done(GraphBuilderDialog.java:675)
	at javax.swing.SwingWorker$5.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
	at sun.swing.AccumulativeRunnable.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[catch] at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

My Computer is equipped with 24 MB RAM.

**Comment by radosuav** [comment]
I haven't seen this error message before but it is being [mentioned on the SNAP forum](https://forum.step.esa.int/search?q=already%20contains%20a%20band%20with%20the%20name%20order%3Alatest) in different contexts, although nothing that looks immediately relevant. Also, it's interesting that it complains about 'confidence_in_duplicate' band, which should not be there after you did the initial subset.

I would suggest to split the graph into three, one for each output product and see if that helps.

**Comment by rasc1974** [comment]
Thank You  for your patience. :)

Now I splitted the original 'Sen3 preperation graph' into three and got the same results as in 3.3.9, with the same error. I can not open the 'LST' and the 'operation_geometry' output. The 'mask' output is opened automatically after finishig the graph.

I´d like to go a step backwards. Perhaps something went wrong while subsetting the Sen3 file. This is the code of the 'subset graph' I created:

![grafik](https://user-images.githubusercontent.com/62097421/78331532-8a06f280-7586-11ea-896c-dca0507a7daf.png)

Only 6 bands are denoted as "source bands", as it is in the original 3.3.9-graph. Hower, in SNAP I can see al lot more bands in the result of my personel 'subset graph':

![SNAP_bands](https://user-images.githubusercontent.com/62097421/78331313-0ea54100-7586-11ea-99fb-045ebc83db38.PNG)

**Comment by radosuav** [comment]
Hi Rainer, do LST, solar_zenith_tn and sat_zenith_tn bands open fine after your first subset operation? The graph itself looks good. Could also be a problem with the particular scene with which you are working. Have you tried with another one?

It looks very much like a SNAP problem so I would suggest posting on SNAP forum and to include your graph and scene name in the post.

**Comment by rasc1974** [comment]
Hi Radoslaw, the error occurs also with a total fresh SEN3 file, which was downloaded from Copernicus open acces Hub, manually. I opened this original file and run my subset graph (after I did some adjustments concerning name and folder). After that I can see a new file and a new folder, with the subset of the original SEN3 file. But when I try to open this new subset file, it´s impossible and I got the error (...observation_geometry' already contains a band with the name 'confidence_in_duplicate'.). So, that has nothing to do with SEN-ET plugin. I´ll try to get [help from STEP-forum](https://forum.step.esa.int/t/sen3-subset-error-already-contains-a-band-with-the-name-confidence-in-duplicate/22186). Thanks so far. Regards, Rainer

**Comment by rasc1974** [comment]
Meanwhile I tried the following:

I made a subset of a SEN3 product (_S3B_SL_2_LST____20190626T091859_20190626T105958_20190627T151103_6059_027_036______LN2_O_NT_003_) by using the SNAP-GUI (Raster -> Subset...) and saved the new subset product as *filename*.dim.

Additionally I adapted the SEN-ET graph "_sentinel_3_pre_processing.xml_" and deleted the subset-part, now it directly switches from "_Read_" to "_Reproject_".

Afterwards I applied that new graph "_sentinel_3_pre_processing_without subset.xml_" to the Sentinel 3 subset-product from the first step. 

The result was the same, three new products were created (_mask, LST, oservation_geometry_), I could open _mask_, but not _LST_ or _observation_geometry_ - and I also get the error, which we already know ("_The Product '!OUTPUT_LST!' already contains a band with the name 'confidence_in_duplicate'._").

Does nodody else have this problem? It does appers on several computers with even fresh installation of SNAP and SEN-ET.

**Comment by radosuav** [comment]
@rasc1974 I have never seen this error before. Are you using SNAP 7 with all the updates applied (you can check by going to Help > Check for Updates in the main menu)? Also, can you open LST or observation_geometry bands after the manual subset (in filename.dim)?

**Comment by rasc1974** [comment]
Yes, my SNAP 7 does an automatic check for uptdate every time it starts.

Here is a screenshot from the LST band of the subset of the original Sentinel 3 product:
<img width="960" alt="SEN3_subset_LST_Screenshot" src="https://user-images.githubusercontent.com/62097421/78896811-728da500-7a71-11ea-8018-182483ab5bda.PNG">

I can see and open, beneath others, the bands _"sat_zenith_tn"_, _"solar_zenith_tn"_, _"longitude_tx"_, _"latitude_tx"_, _"cloud_in"_ and _"LST"_.

**Comment by rasc1974** [comment]
I opened an issue in the STEP-forum, a week ago but didn´t get any response, until now (https://forum.step.esa.int/t/sen3-subset-error-already-contains-a-band-with-the-name-confidence-in-duplicate/22186). 

Did you perhaps try to follow my actions and do the same on a Windows 10 system? I tried it on several PC with Windows 10. I open a Sentinel 3 product and use a graph to make a subset of a region and of bands. You can find the code of the graph.xml above.

I always get the same result (a new *.dim - file is written and new *.data - folder is created), but I can not open the new subset-product in SNAP! I really like to solve this issue, because me and my working group wish to use Sen-ET for irrigation sceduling.

**Comment by radosuav** [comment]
Hi Rainer, I bumped up your question on the SNAP forum. In the meantime could you try two things:
1. Delete geodetic_in.nc file in the .SEN3 directory before running your subset (see [this post](https://forum.step.esa.int/t/using-subsetop-gettargetproduct-to-clip-s3-slstr-lst-data/11906/12) - although it should have been fixed in SNAP 7).
2. Put two consecutive subset operators in your graph, with the first one performing just band subsetting, and the second one just AOI subsetting.

**Comment by rasc1974** [comment]
Hi, when I delete _geodetic_in.nc_ the product unfortunately can not be opened in SNAP.

But... today I tried this [code for sentinel_3_pre_processing](https://drive.google.com/open?id=1Bs6cY6IH-lBzbdiyUZlCLZrHQ_nMQuZl):

...and the result is, that three new products have been created (mask, LST, observation geomerty). All of them open automatically in SNAP after finishing the calculation. However, the subseting of bands did not work with LST and observation geometry.

![grafik](https://user-images.githubusercontent.com/62097421/80341731-4476d600-8863-11ea-9db3-33b018eead13.png)

I´m quite shure, that I didn´t change anything to the original Sentinel_3_pre_processing-code, beside insertion of the region and the folder locations/product names. Nevertheless, compared to the situation before this looks like a step forward. I´ll it try with more SEN 3-products.

**Comment by rasc1974** [comment]
...ok, now it really works with several Sentinel 3 products, except the band subsetting. But that can be done quick and easy by GUI (Raster > subset). However, I still don´t know, what caused the error before.

That´s ok for me, now - so this issue could be closed. Thanks a lot!

**Comment by radosuav** [comment]
Glad to hear that it works :) The main difference which I see is that you inserted GeoRegion into all the subset operators. In theory this should not change anything (multiple subsetting to the same AOI shouldn't make a difference) but sometimes SNAP works in mysterious ways...
