### ISSUE TITLE
Target product {fraction of Green]

### ISSUE THREAD

**Issue by AymanRahman** [DHI-GRAS/sen-et-snap-sta#16]
Dear SIrs,
By using [estimate fraction of vegetation  in green] what have I to write in target product name ? output image?
I write in target product  " !OUTPUT_fraction_green_vegtation!"
I got wornning massage 'target product is required as adapter s templet, non is provided'
would you please explain what is the correct
Thank you so much

**Comment by AymanRahman** [comment]
It is the same for "leaf reflectance  and "transmittance"
 'target product is required as adapter s templet, non is provided'

**Comment by Ioannis-Faraslis** [comment]
"Target product" and "Output image" must have exactly the same name.  Plus
in the "Output image" at the end of the name you must write ".dim". For example
"Fraction_Vegetation.dim"

**Comment by AymanRahman** [comment]
Thank you so much
I continue and by estimate map of vegetation structure parameter
I press RUn but nothing happened
sometime massage "try to open target product"

**Comment by AymanRahman** [comment]
Thank you so much

**Comment by Ioannis-Faraslis** [comment]
Pay attention to "Land cover band " and look-up table" inputs.
Please see the attached file
Regards



Quoting AymanRahman <notifications@github.com>:
