### ISSUE TITLE
Problem with Download ECMWF ERA5 reanalysis data operator

### ISSUE THREAD

**Issue by rasc1974** [DHI-GRAS/sen-et-snap-sta#18]
Hi, I´m trying to process step 3.3.12 now but unfortunately got the following result:

![grafik](https://user-images.githubusercontent.com/62097421/80379821-e831a780-889e-11ea-921e-e4d16d98d003.png)

Does anybody have an idea, what is the reason for this? 

Regards,
Rainer

**Comment by radosuav** [comment]
Hi Rainer, it appears that your input netCDF file does not have a time dimension. Can you open it in SNAP and check if 'time' exists in Metadata > Variable_Attributes:
![image](https://user-images.githubusercontent.com/4759850/80408604-ba148d80-88c7-11ea-85a2-fa6af667ece4.png)
If it does not exists then something went wrong in the previous step (Download ECWMF ERA5 reanalysis data). Could you repeat that step and post the output text here.

**Comment by rasc1974** [comment]
Hi Radoslav, as I understand this is a problem with the CDS API file. I guess the meteodata folder have been created but data has not been downloaded:

![Meteo_error](https://user-images.githubusercontent.com/62097421/80451235-9da63e80-8923-11ea-9abc-e2b27f7cddae.PNG)


However, the CDS API file is located in my home-folder:

![Explorer_2](https://user-images.githubusercontent.com/62097421/80451109-4ef8a480-8923-11ea-85d0-256e6503e84c.PNG)

...but I can´t find a .cdsapirc within my .snap folder, although I was quite sure to have followed this [instructions](https://confluence.ecmwf.int/display/CKB/How+to+install+and+use+CDS+API+on+Windows).

**Comment by radosuav** [comment]
The cdsapi Python package should have been installed with the Sen-ET bundle and should be present in username\\.snap\auxdata\sen-et-conda-Win64\Lib\site-packages\cdsapi. The API key (.cdsapirc file) should be in your user folder. So maybe all you need to do is to rename "cdsapi.cdsapirc" to ".cdsapirc".

**Comment by rasc1974** [comment]
Ok thanks. After renaming of the *.cdsapirc file and downloading of meteodata I´ve got several warnings and a new error, now -  and the preparation of the meteodata (step 3.3.13) aborts: 

![Meteo_warnings and error](https://user-images.githubusercontent.com/62097421/80453940-810d0500-8929-11ea-8546-acc6519e2dd0.PNG)

**Comment by radosuav** [comment]
It looks like a problem with you elevation file. Could try to open it in QGIS.

**Comment by rasc1974** [comment]
Hi, here is the elevation in SNAP:

![grafik](https://user-images.githubusercontent.com/62097421/80567977-69e81900-89f6-11ea-955d-f606e9f1b9c5.png)

...and here it is in QGIS:

![grafik](https://user-images.githubusercontent.com/62097421/80568057-90a64f80-89f6-11ea-86c4-666c0da5ea10.png)

However, the data seem to be wrong. It should be around 70 m above sea level, not 102 - 190!

I just executed the Sentinel-2 preprocessing graph and the Add elevation graph once again and got the same result as above

**Comment by rasc1974** [comment]
Here´s a screenshot from an online tool to find out the height above sea level:

![grafik](https://user-images.githubusercontent.com/62097421/80570370-eaa91400-89fa-11ea-9d13-e3d79b8d7020.png)

In general the pattern produced by SNAP is correct, but the values don´t fit to the reality (if I understand the values correctly?!).

**Comment by radosuav** [comment]
Hi, the DEM should be SRTM 1sec HGT as downloaded by the SNAP "Add elevation band" operator. You can double check by doing this manually through Raster > DEM Tools > Add elevation band. So it appears that one of the elevation layers is incorrect but this will not have a big impact on the meteorological values.

Regarding the error, I think the hint might be in "1-pixel width/height files not supported" message. How big is the AOI for which you download the SRTM data? The spatial resolution of ERA5 data is 0.25 degrees (around 25-30 km) so if your AOI is smaller then 1-pixel raster is downloaded and it cannot be processed by SNAP geotiff driver. Try expanding the AOI to be at least 1 by 1 degree. When performing the thermal sharpening later it is good to have a larger AOI anyway, at least 50 by 50 S3 pixels (so around 50 by 50 kilometers).

**Comment by rasc1974** [comment]
Dear Radoslav,
thank You, I see. My point of interest is located in the south west of a Sentinel 2 tile. I can indeed choose a larger AOI to cover at least 1 entire ERA5 pixel, but this entire ERA5 pixel does not contain my point of interest. It is not possible to cover that ERA5 pixel that contains my point of interest in the south west corner of that particular Sentinel 2 tile, completely. A small part of the ERA5 pixel is not covered. I guess the reanalysis of the ERA 5 data is only applied to entire pixels covered by the Sentinel 2 elevation? See this screenshot from QGIS for a better understanding:

![grafik](https://user-images.githubusercontent.com/62097421/81402486-cb646200-9131-11ea-8c1f-b400e89d0784.png)

Do I have to combine at least 2 Sentinel 2 tiles in that case (if they are available)? 

Best regards
Rainer

**Comment by radosuav** [comment]
Hi Rainer,
It's not a problem that the ERA5 dataset extends beyond Sentinel-2 scene. [To adjust the air temperature based on elevation](https://github.com/DHI-GRAS/sen-et-snap-scripts/blob/master/ecmwf_utils.py#L65-L83) we first bring the ERA5 air temperature down to sea level using ERA5 geopotential height, then resample, reproject and subset based on the S2 scene and finally apply the elevation correction using high-resolution DEM. 

But looking at the screenshot above, you will have a problem when sharpening the LST because it appears that there is no overlap between your S2 subset and S3 LST. The sharpening only works for areas in which S2 and S3 scenes overlap.

**Comment by rasc1974** [comment]
Ok, thank You so far! I´ll close this issue now, because I managed this problem. In the screenshot You can see different overlapping layers. The Sentinel 2 tile covers the Sentinel 3 LST completely.

Best regards,
Rainer
