### ISSUE TITLE
Download ERA5 data problems - netCDF?

### ISSUE THREAD

**Issue by georgeboldeanu** [DHI-GRAS/sen-et-snap-sta#2]
Why i can't download data as a form of Netcdf directly and I must provide a netcdf to download  the Era5 data. It's illogical to me in this point. For that i must create a netcdf with all the variables and dimensions, but for example if i want to change the variables or dimensions to the next download  I must create another Netcdf again. I really don't find the logic.

![era52](https://user-images.githubusercontent.com/34105846/71878664-daf87d80-3134-11ea-91fd-78101404f819.jpg)

**Comment by j08lue** [comment]
Sorry if the description is misleading. The NetCDF file does **not** need to exist. It just needs to be a file name with extension `.nc`.

**Comment by georgeboldeanu** [comment]
@j08lue Sorry i didnt close the issues because even i get past the .nc problem i get the followin error:
**ERROR:Missing/incomplete configuration file: $USERPROFILE/.cdsapirc** . I configured correctly the .cdsapirc file and tested with the associated python. All it works fine, i downloaded some test data. But when i use it in SNAP all the time i get that error. You have any idea what can it be?

**Comment by j08lue** [comment]
Right. Seems like the `$USERPROFILE` variable is not resolved. Could you please close this issue and open a new one for this, just to keep things separate? Then we'll look into it.

**Comment by georgeboldeanu** [comment]
Cheers!
