### ISSUE TITLE
Problem with Estimate land surface energy fluxes operator (3.3.16)

### ISSUE THREAD

**Issue by rasc1974** [DHI-GRAS/sen-et-snap-sta#21]
Hi,
I tried to process step 3.3.16 but unfortunately got an error, which I don´t understand.... Can anyone give an advice how to solve this, please?
Best Regards,
Rainer

Here´s a screenshot of the execution output:
![grafik](https://user-images.githubusercontent.com/62097421/81659134-b80b0c80-9439-11ea-9022-58ac63485a16.png)

...and here´s a screenshot of the I/O Parameters:
![grafik](https://user-images.githubusercontent.com/62097421/81659227-cf49fa00-9439-11ea-8b48-701ddb6bdc7e.png)

**Comment by radosuav** [comment]
It looks like not all your input images are of the same dimension. Probably the LST view zenith angle product is at the original S3 resolution and not the output of "Warp to template" operator (3.3.1.10).

**Comment by rasc1974** [comment]
Yes, you´re right. I underrated the warp to template operator, I guess... Due to Your advices I produced a map of daily evapotranspiration for a scene in Germany. Thank You!! :)

![grafik](https://user-images.githubusercontent.com/62097421/82017156-cdbf4280-9682-11ea-8b4c-b93a0e7b0c4b.png)
