### ISSUE TITLE
error by download S2

### ISSUE THREAD

**Issue by AymanRahman** [DHI-GRAS/sen-et-snap-sta#24]
Dear Sirs,
when I start to download S2 I got the following massage :
ERROR:HTTPSConnectionPool(host='scihub.copernicus.eu', port=443): Max retries exceeded with url: /apihub/search?format=json&rows=100&start=0 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
would you please help me to correct the error
Thank you

**Comment by radosuav** [comment]
Looks like an error on SciHub server. Please retry in a couple of hours.
