### ISSUE TITLE
download S3

### ISSUE THREAD

**Issue by AymanRahman** [DHI-GRAS/sen-et-snap-sta#25]
Dear Sirs
I have always a connection problem to download S3 by SNAP, 
would you please explain me how can I download S3 from COAH (product type instrument) because I have two different images
Thank you

(SL2_LST__) (SLSRT)  is it OK?

**Comment by radosuav** [comment]
Hi, yes this is correct. Product type is SL2_LST___ and the instrument is SLSTR.

**Comment by radosuav** [comment]
The download problem could be because those files can be very large for historical images, close to 2 GB. If you have unstable connection then you might hit the same issue when downloading from COAH.

**Comment by AymanRahman** [comment]
the results of search for S3 two types: one as image for big area around AOI and the second as image long around earth . which one have I to choose?

**Comment by radosuav** [comment]
For historical data usually only the second (larger) image is available. If you are looking at more recent data and the smaller image is avaiable then it should be fine to download it.

**Comment by radosuav** [comment]
If the issue is still not resolved then please move the discussion to the [Sen-ET category on SNAP forum](https://forum.step.esa.int/c/snap/sen4et/).
