### ISSUE TITLE
Produce maps of vegetation structural parameters

### ISSUE THREAD

**Issue by AymanRahman** [DHI-GRAS/sen-et-snap-sta#26]
Dear SIrs,
I try to produce maps of vegetation structural parameters  but no response
my data work is as folllow
![map_ver_3](https://user-ima
![map_ver_1](https://user-images.githubusercontent.com/43352074/85434584-ededf580-b58e-11ea-868d-b11a7db6d202.png)
![map_ver_2](https://user-images.githubusercontent.com/43352074/85434602-f5150380-b58e-11ea-889c-1359a8998f3b.png)

ges.githubusercontent.com/43352074/85434527-d9116200-b58e-11ea-9ced-57796a946bde.png)

I change the band name as in image but no sccess

would u please help me
thank you

**Comment by radosuav** [comment]
What message is printed when you press run?

**Comment by AymanRahman** [comment]
I press Run but nothing happened at all , as in foto over

**Comment by radosuav** [comment]
Did you provide "Output image" filename at the bottom of Processing Parameters tab?

**Comment by radosuav** [comment]
If the issue is still not resolved then please move the discussion to the [Sen-ET category on SNAP forum.](https://forum.step.esa.int/c/snap/sen4et/)
