### ISSUE TITLE
S3 Preprocessing

### ISSUE THREAD

**Issue by janardanroy** [DHI-GRAS/sen-et-snap-sta#27]
When I opened S3 image in snap, I can not see sat_zenith_tn,
solar_zenith bands. So , how will I get these bands in observation_geometry product?
![Screenshot from 2020-07-02 16-42-16](https://user-images.githubusercontent.com/39547169/86353630-2ecbc580-bc85-11ea-81b8-587705862b7c.png)

**Comment by radosuav** [comment]
A new category has been created on [SNAP forum](https://forum.step.esa.int/c/snap/sen4et/) for such discussion. Please move this question there and while doing that provide more details describing your issue.
