### ISSUE TITLE
Download S2 Authontification issue 

### ISSUE THREAD

**Issue by khouakhi** [DHI-GRAS/sen-et-snap-sta#28]
I keep getting HTTP status 401 Unauthorized even if my scihub.copernicus username and password are correct. 

C:\Users\e806872\AppData\Local\Temp>"C:\Users\e806872\.snap\auxdata\sen-et-conda-Win64\sen-et-snap-scripts\\..\python.exe" "C:\Users\e806872\.snap\auxdata\sen-et-conda-Win64\sen-et-snap-scripts\\sentinel_data_download.py" --aoi_geojson "C:\Users\e806872\roi_geojson.geojson" --start_date 20190512 --end_date 20200610 --platform Sentinel-3 --download_path C:\Users\e806872 --username XXXX --password YYYYY --download_images false --cloud_cover_percentage 99 --limit_tiles $limit_tiles 
Searching for scenes on https://scihub.copernicus.eu/apihub

HTTP status 401 Unauthorized: 
# HTTP Status 401 - Full authentication is required to access this resource
 **type** Status report
 **message** _Full authentication is required to access this resource_
 **description** _This request requires HTTP authentication._
* * *
### Apache Tomcat/8.0.36
beginPosition:[2019-05-12T00:00:00Z TO 2020-06-10T23:59:59Z] filename:* instrumentshortname:SLSTR platformname:Sentinel-3 productlevel:L2 footprint:"Intersects(MULTIPOLYGON(((-74.1259 10.8227,-74.1297 10.8225,-74.1298 10.8215,-74.1305 10.8215,-74.1305 10.8216,-74.1306 10.8216,-74.1306 10.8217,-74.1308 10.8217,-74.1308 10.8219,-74.1314 10.8218,-74.1314 10.8227,-74.1340 10.8226,-74.1343 10.8219,-74.1358 10.8219,-74.1358 10.8212,-74.1371 10.8212,-74.1373 10.8213,-74.1372 10.8220,-74.1372 10.8222,-74.1373 10.8223,-74.1376 10.8224,-74.1378 10.8223,-74.1380 10.8223,-74.1381 10.8226,-74.1381 10.8228,-74.1380 10.8231,-74.1373 10.8230,-74.1369 10.8231,-74.1367 10.8231,-74.1366 10.8236,-74.1366 10.8237,-74.1366 10.8239,-74.1366 10.8241,-74.1365 10.8243,-74.1364 10.8245,-74.1363 10.8247,-74.1354 10.8247,-74.1353 10.8252,-74.1353 10.8254,-74.1351 10.8255,-74.1348 10.8255,-74.1346 10.8255,-74.1346 10.8263,-74.1363 10.8264,-74.1378 10.8264,-74.1379 10.8265,-74.1380 10.8265,-74.1382 10.8265,-74.1385 10.8265,-74.1387 10.8265,-74.1389 10.8264,-74.1391 10.8266,-74.1392 10.8269,-74.1393 10.8271,-74.1391 10.8272,-74.1385 10.8273,-74.1383 10.8274,-74.1379 10.8275,-74.1376 10.8276,-74.1372 10.8276,-74.1367 10.8277,-74.1362 10.8277,-74.1357 10.8276,-74.1352 10.8276,-74.1350 10.8274,-74.1348 10.8272,-74.1347 10.8271,-74.1344 10.8272,-74.1342 10.8271,-74.1338 10.8271,-74.1336 10.8272,-74.1334 10.8273,-74.1332 10.8274,-74.1330 10.8276,-74.1329 10.8275,-74.1326 10.8278,-74.1325 10.8287,-74.1329 10.8292,-74.1329 10.8293,-74.1332 10.8295,-74.1331 10.8296,-74.1329 10.8299,-74.1326 10.8300,-74.1325 10.8301,-74.1325 10.8303,-74.1325 10.8304,-74.1324 10.8307,-74.1325 10.8309,-74.1324 10.8311,-74.1322 10.8312,-74.1321 10.8313,-74.1320 10.8313,-74.1318 10.8313,-74.1318 10.8314,-74.1307 10.8314,-74.1296 10.8314,-74.1291 10.8314,-74.1287 10.8314,-74.1282 10.8314,-74.1278 10.8313,-74.1276 10.8313,-74.1269 10.8312,-74.1266 10.8311,-74.1262 10.8312,-74.1256 10.8312,-74.1251 10.8311,-74.1246 10.8310,-74.1242 10.8308,-74.1238 10.8307,-74.1235 10.8302,-74.1232 10.8295,-74.1232 10.8294,-74.1231 10.8291,-74.1227 10.8278,-74.1221 10.8255,-74.1213 10.8231,-74.1215 10.8229,-74.1217 10.8229,-74.1217 10.8228,-74.1212 10.8213,-74.1215 10.8213,-74.1210 10.8208,-74.1206 10.8201,-74.1205 10.8198,-74.1196 10.8188,-74.1191 10.8185,-74.1186 10.8181,-74.1183 10.8177,-74.1179 10.8170,-74.1178 10.8161,-74.1203 10.8162,-74.1206 10.8169,-74.1206 10.8173,-74.1209 10.8173,-74.1213 10.8173,-74.1218 10.8173,-74.1220 10.8173,-74.1236 10.8171,-74.1240 10.8182,-74.1245 10.8190,-74.1247 10.8211,-74.1254 10.8211,-74.1255 10.8211,-74.1257 10.8213,-74.1259 10.8216,-74.1259 10.8227))))"
Found 0 scenes
Finished tool execution in 0 seconds

**Comment by radosuav** [comment]
Recently a [Sen-ET section](https://forum.step.esa.int/c/snap/sen4et/37) opened on SNAP forum. Please direct such issues there for best chance of getting support form the community. But first I would recommend to retry download (maybe scihub was down when you first try) and to contact SciHub user support.

**Comment by radosuav** [comment]
Recently a [Sen-ET section](https://forum.step.esa.int/c/snap/sen4et/37) opened on SNAP forum. Please direct such issues there for best chance of getting support form the community. But first I would recommend to retry download (maybe scihub was down when you first try) and to contact SciHub user support.
