### ISSUE TITLE
Missing/incomplete configuration file

### ISSUE THREAD

**Issue by priya-sharma-07** [DHI-GRAS/sen-et-snap-sta#29]
getting below error while downloading ERA5 dataset in .cdsapirc file.
and my format of .cdsapirc file is as below.
url: {api-url}
key: {uid}:{api-key}
![p1](https://user-images.githubusercontent.com/65880337/90275324-b78e7180-de7f-11ea-9bdd-c12c7f736519.png)
![p2](https://user-images.githubusercontent.com/65880337/90275329-b9f0cb80-de7f-11ea-8921-c5513958187a.png)
![p3](https://user-images.githubusercontent.com/65880337/90275331-ba896200-de7f-11ea-82ac-4cf0ae8d83a8.png)

please help me reslove this issue

**Comment by radosuav** [comment]
Please direct such questions to [Sen-ET section of the SNAP forum](https://forum.step.esa.int/c/snap/sen4et/37) for best chance of getting support form the community.
