### ISSUE TITLE
Problem with 3.35 Estimate leaf reflectance and transmittance

### ISSUE THREAD

**Issue by rasc1974** [DHI-GRAS/sen-et-snap-sta#30]
Hi,

Im trying to process step 3.3.5 but get an error:

![grafik](https://user-images.githubusercontent.com/62097421/97698147-5f433500-1aa8-11eb-9802-1166f159056a.png)

This is new to me, because in the past this step worked fine. I upgraded to SNAP 8, meanwhile. I´m using SEN-ET 1.0.1.
Can someone give an advice, perhaps?

Best regards
Rainer

**Comment by radosuav** [comment]
Hi,
Please post your question on the [Sen-ET section of SNAP forum](https://forum.step.esa.int/c/snap/sen4et/37). It looks like a problem with Snappy.
