### ISSUE TITLE
Segmentation Fault in Fraction of Green Vegetation estimation.

### ISSUE THREAD

**Issue by janardanroy** [DHI-GRAS/sen-et-snap-sta#31]
I have completed S2 and S3 processing as far the Following link: 

[https://github.com/DHI-GRAS/sen-et-snap-scripts/blob/master/auxdata/graphs/](url) 

Then calculated Leaf reflectance and Transmittance. But when I am running Fraction of Green Vegetation estimation , I am getting **"Segmentation fault"** error. I have tried with altering minimum fraction of vegetation which is green, but got the same error again and again.

![Screenshot from 2021-08-27 10-22-48](https://user-images.githubusercontent.com/39547169/131074171-966eb9c7-8016-4f14-a379-8abb0ee139c2.png)

![Screenshot from 2021-08-27 10-22-59](https://user-images.githubusercontent.com/39547169/131074190-fa907fba-2056-4929-a98f-c83a810fe615.png)

How to overcome this error?

**Comment by radosuav** [comment]
This is being discussed on [SNAP forum](https://forum.step.esa.int/t/segmentation-fault-on-fraction-of-green-vegetation/24915/7).
