### ISSUE TITLE
Solution: Download sentinel data

### ISSUE THREAD

**Issue by EmanuelCastanho** [DHI-GRAS/sen-et-snap-sta#33]
If you are unable to download sentinel products using **Download sentinel data**, you must go to C:\Users\your_username\\.snap\auxdata\sen-et-conda-Win64\sen-et-snap-scripts\find_sentinel_images.py and change the **hub_address** to `hub_address="https://apihub.copernicus.eu/apihub/",` on all functions!

**Comment by EmanuelCastanho** [comment]
Also, the progress bar needs to be improved, during the download the **Starting tool execution** remains at 0%.

**Comment by radosuav** [comment]
Hi @EmanuelCastanho, thanks for your tips and observations (also in #32 ). The Sen-ET project has concluded and the plugin is not being developed at the moment. The best location to solve issue and share tips is at the SNAP forum: https://forum.step.esa.int/c/snap/sen4et/37.
