### ISSUE TITLE
Error for downloading ECMWF ERA5 reanalysis data

### ISSUE THREAD

**Issue by AidaTaghavi** [DHI-GRAS/sen-et-snap-sta#34]
Hi,
I got the error below for downloading ECMWF ERA5 reanalysis data.
Would you please let me know how to solve it?
![Capture](https://user-images.githubusercontent.com/38229771/147552165-c836f8ef-bc13-450f-ab73-29f6f17978f1.PNG)

**Comment by radosuav** [comment]
See https://forum.step.esa.int/t/error-for-downloading-ecmwf-era5-reanalysis-data/34341
