### ISSUE TITLE
Why senET is no longer officilaly supported?

### ISSUE THREAD

**Issue by frzambra** [DHI-GRAS/sen-et-snap-sta#35]
I just read in the webpage of senET (https://www.esa-sen4et.org/outputs) that the plugin will not be longer officially supported. Any advice on what that means? Should I continue using senET?

Cheers!

Francisco

**Comment by radosuav** [comment]
Please see [reply](https://forum.step.esa.int/t/about-the-sen-et-category/24052/7) in your forum post.
