### ISSUE TITLE
operator 3.3.15 Estimate net shortwave radiation operator not found layer "solar_zenith_tn"

### ISSUE THREAD

**Issue by alveniz** [DHI-GRAS/sen-et-snap-sta#8]
Error in operator 3.3.15 "Estimate net shortwave radiation operator" not found layer "solar_zenith_tn".

The preprocessing graph of Sentinel-2 output the image "!OUTPUT_sun_zenith_angle!.dim" with band "sun_zenith", and the operator 3.3.15 expected the name band "solar_zenith_th".

I change the name of band in the "!OUTPUT_sun_zenith_angle!.dim" image and the operator its works, but this is the band correct?, or any problem in preprocessing graph of Sentinel-2.

thanks

**Comment by radosuav** [comment]
The net shortwave radiation is estimated at the time of the Senitnel-3 overpass and therefore this input should come from Sentinel-3 ("HR observation geometry" in Figures 2.2 and 2.4). There is a mistake in section 3.3.15 of the user manual. Thanks for the report!

**Comment by radosuav** [comment]
Updated [user manual v1.0.1](http://esa-sen4et.org/download/sen-et-user-manual-for-v1-0/) has now been published.
