### ISSUE TITLE
No graphs found

### ISSUE THREAD

**Issue by rasc1974** [DHI-GRAS/sen-et-snap-sta#9]
Hi, 
I installed SEN-ET as a plugin in SNAP and can download Data from Sentinel 2 and 3 and the required meteorological data with the respective operators. But when it comes to load the graphs I can´t find them anywhere within the SNAP Graph builder. Can You give an advice, please? 
Best Regards
Rainer

**Comment by radosuav** [comment]
Hi Rainer,
You can find the graphs in username/.snap/auxdata/sen-et-snap-<OS>64/sen-et-snap-scripts/auxdata/graphs folder. Also please have a look at section 3.3 of the user manual.

**Comment by rasc1974** [comment]
Ok, wondefull - I detected them, now. Thanks a lot!
Best regards
Rainer

**Comment by rasc1974** [comment]
Hi,

once again I have a problem, to get running properly: it´s the Import-error You described in chapter 3.4.4.

"  import jpyutil
ModuleNotFoundError: No module named 'jpyutil'"

I tried different versions of python (3.6.0, 3.6.8) and configured SNAP to use with Python but it´s always the same. 

Best regards
Rainer
